### ISSUE TITLE
Kompatibilitätsprobleme mit verschiedenen Schulen

### ISSUE THREAD

**Issue by SachsenspieltCoding** [Julius-Babies/VPlanPlus#74]
Hallo @Julius-Babies,
zunächst einmal: Unglaublich starke App! Ich habe selber mal eine eigene Vertretungsplan App gemacht ([Vertretungsapp](https://github.com/Vertretungsapp/app)) und weiß daher wie Müll diese API ist.

Und weil die API so Müll ist, funktionieren nicht alle Schulen bei dir. Ich weiß nicht auf welche Pläne du konkret gehst, aber ich habe sowohl die Testschule (10000000) als auch meine eigene getestet und bei keinem der beiden Daten bekommen können. Meine Schule konnte ich sogar nichtmal hinzufügen, da es bereits beim Anmelden einen Unbekannten Fehler gab.

Wenn du irgendwelche Hilfe brauchst im Bezug auf die API, dann steh ich dir gerne zur Seite.

**Comment by Julius-Babies** [comment]
Keine Daten... meint das die Anzeige "Keine Daten verfügbar", "Es gibt noch keine V-Pläne für das Datum etc..."? Du musst nach dem Hinzufügen der Schule einmal manuell synchronisieren, indem du auf das "Profil"symbol tippst und dann auf Sync.

**Comment by Julius-Babies** [comment]
> Meine Schule konnte ich sogar nichtmal hinzufügen, da es bereits beim Anmelden einen Unbekannten Fehler gab.
Wer hosted die? Aktuell unterstützt VPP nur stundenplan24.de Instanzen.

**Comment by SachsenspieltCoding** [comment]
Meine Schule geht auch über stundenplan24.de

Die Beispielschule liefert tägliche Demo Daten, ganz praktisch.
Schulnummer: 10000000
Benutzer: schueler / lehrer
Passwort: <irgendetwas zufälliges>

Zum Thema Keine Daten, auch nach dem Refresh kommt der gleiche Screen.
![grafik](https://github.com/Julius-Babies/VPlanPlus/assets/59836848/dc041f04-6a70-48c3-8f2e-7d812b8b4387)
Anhand der Logs habe ich gesehen, dass du die Wochenpläne nutzt. Die sind bspw. bei den mir bekannten Schulen gar nicht vorhanden. Selbst die Beispielschule scheint keine zu haben.
![grafik](https://github.com/Julius-Babies/VPlanPlus/assets/59836848/6a918a1e-08a9-4064-b0a1-523930697797)

Die Zugangsdaten zu meiner Schule haben auch definitiv gepasst (gibt man falsche ein kommt auch der richtige Error).
Die Logs zeigen eine gleiche Symptomatik
![grafik](https://github.com/Julius-Babies/VPlanPlus/assets/59836848/b7a3b321-dcb4-41c2-960a-5488bacf0d44)

**Comment by Julius-Babies** [comment]
Es gibt ja WPlan_<datum>.xml und SPlan_<datum>.xml oder so ähnlich. Aktuell benutze ich ausschließlich WPlan Daten, meine Schule stellt die halt bereit und ich hatte bisher nicht die Gelegenheit, andere Schulen mit anderen Modules zu testen. Ich werde irgendwann die SPlan Daten implementieren, allein schon, weil die App nur über Tage mit Vertretungsplänen bescheid weiß und demnach keinen Fallback Stundenplan wenn kein V-Plan für ein bestimtmes Datum existiert.

**Comment by SachsenspieltCoding** [comment]
Okay, musst schauen. Ich hab immer mit den mobil/mobdaten gearbeitet, da die meiner Erfahrung nach am Zuverlässigsten sind

`https://stundenplan24.de/10000000/mobil/mobdaten/Klassen.xml`
bzw.
`https://stundenplan24.de/10000000/mobil/mobdaten/PlanKl20231124.xml`

**Comment by SachsenspieltCoding** [comment]
Die sollten auf jeden Fall immer funktionieren, weil das die Endpoints sind die VpMobil auch nutzt.
Du kannst ja das mit den Wochenplänen drin lassen, und nutzt dann die App Endpoints als Fallback.

**Comment by Julius-Babies** [comment]
Ich könnte glaube ich sogar komplett darauf umsteigen. Die App hat ja im Endeffekt jede Schule. Die Daten, die ich benötige, sind alle enthalten. Eigentlich "nur" XML-Parser und URLs anpassen.

**Comment by Julius-Babies** [comment]
Noch eine Frage, die Klassen und Stundenkonmbinationen wurden dir alle im Onboarding angezeigt, oder? Falls ja, dann sind die Basisdaten wenigstens unberührt von dem kleinen Refactoring.

**Comment by SachsenspieltCoding** [comment]
Das hatte nur bei der Beispielschule funktioniert, bei meiner nicht

**Comment by Julius-Babies** [comment]
...Also sind die Basisdaten auch betroffen. Na gut, wenn ich mich darauf verlassen kann, dass die entsprechenden Schnittstellen garantiert existieren, werde ich dorthin migrieren.

**Comment by SachsenspieltCoding** [comment]
Muss ja wenn VpMobil drauf zugreift

**Comment by Julius-Babies** [comment]
Sollte mit der neuesten Version behoben sein, die Beispielschule funktioniert und alles, was nur mit Stundenplan Version 5 arbeitet soll im kommenden Jahr migriert werden. Es gibt seitens Indiware schon Arbeiten an einem Nachfolgesystem für Wochenplan 6 und VpMobil24 (heißt dann VpMobilPlus :D) richtig mit API und Rechtemanagement. Stundenplan 5 ist seitens Indiware schon als Legacy abgestempelt.

**Comment by SachsenspieltCoding** [comment]
> Sollte mit der neuesten Version behoben sein, die Beispielschule funktioniert und alles, was nur mit Stundenplan Version 5 arbeitet soll im kommenden Jahr migriert werden. Es gibt seitens Indiware schon Arbeiten an einem Nachfolgesystem für Wochenplan 6 und VpMobil24 (heißt dann VpMobilPlus :D) richtig mit API und Rechtemanagement. Stundenplan 5 ist seitens Indiware schon als Legacy abgestempelt.

Kann irgendjemand Indiware bitte einfach schließen. Warum bekommen die bzw. er (ist ja gefühlt eine Einzelperson) es nicht gebacken eine vernünftige App auf den Markt zu kriegen? Und warum zur Hölle unterstützt der Freistaat so ein Pfusch überhaupt? Fragen über Fragen

**Comment by Julius-Babies** [comment]
Ja, aber es hat sich durchgesetzt. Wie dem auch sei, ich hoffe stark darauf, dass die API wirklich angenehm zu Benutzen sein wird. Es sind übrigens mehrere Personen, hatte gestern mit denen telefoniert.

**Comment by SachsenspieltCoding** [comment]
Hast du wegen deiner App da angerufen?

**Comment by Julius-Babies** [comment]
Jo, ich wollte von denen noch mal eine Einverständniserklärung haben, ob ich meine App in den Play Store bringen darf - ich benutze ja deren Server. Reverse Engineering ist an sich legal, aber sicher ist sicher. habe ein Zusage erhalten, soll aber einen User Agent angeben, falls da irgendwelche Auffälligkeiten auftreten, dass sie mich kontaktieren können. Die hatten wohl schon ihre Probleme mit Drittanbieterapps, die sekündlich auf deren Servern zugegriffen haben.

**Comment by Julius-Babies** [comment]
```
Sehr geehrter Herr Babies,

vielen Dank, dass Sie erst fragen, bevor Sie Ihre App veröffentlichen.

Grundsätzlich haben wir nach aktuellem Stand nichts dagegen, wenn Sie auf die Daten zugreifen, solange dies nicht z. B. minütlich geschieht.
Beachten Sie dabei, dass Sie im Zweifelsfall die Erlaubnis der Schulleitung einholen, da Sie ja dann die Daten der Schule verarbeiten.
Weiterhin wäre es günstig, wenn Sie uns den User-Agent der App mitteilen, damit wir bei Auffälligkeiten mit Ihnen in Kontakt treten können.

Perspektivisch werden wir selber eine neue App entwickeln (die dann auch ein "Plus" am Namensende hat und eigentlich sind wir schon in der Entwicklung) und dann den Zugriff auf den Server per API steuern.

Bei weiteren Fragen rufen Sie uns bitte an.
```

**Comment by SachsenspieltCoding** [comment]
Ah okay cool.
Meine App ist in der Veröffentlichung leider gescheitert, da ich keine Möglichkeit habe sie in den Play Store zu pushen und der App Store (Apple) ist da ja nur noch restriktiver (und teurer)

**Comment by SachsenspieltCoding** [comment]
@Julius-Babies Also die Testschule funktioniert wie von dir gesagt jetzt bestens. Meine eigene funktioniert jedoch noch nicht, das liegt aber vermutlich daran, dass meine Schule zu wenig Information liefert. Musst du selber entscheiden ob du es fixt oder nicht und in welcher Prio

![grafik](https://github.com/Julius-Babies/VPlanPlus/assets/59836848/50ba7a73-6954-4142-88c9-c33072238c55)

**Comment by Julius-Babies** [comment]
Hi, bezüglich der Kompatibilitätsprobleme. Besteht bei deiner Schule die Möglichkeit als `schueler` auch die Lehrer- und Raumpläne anzuzeigen?

**Comment by Julius-Babies** [comment]
Ist zumindest ein Problem, was so wirkt wie das, was du im letzten Screenshot geteilt hast. Diese Daten sind nicht in jeder Schule für `schueler` zugänglich. Daran arbeite ich gerade in #125

**Comment by Julius-Babies** [comment]
Sonst versuche mal die Version (v0.8-alpha). Die aktuellste Version findest du auf der [Homepage](https://vplanplus.jvbabi.es/) des Projektes.

**Comment by SachsenspieltCoding** [comment]
> Hi, bezüglich der Kompatibilitätsprobleme. Besteht bei deiner Schule die Möglichkeit als `schueler` auch die Lehrer- und Raumpläne anzuzeigen?
> 
> 
> 
> Bei Wochenplan 6 gibt es ein Dropdown, in welchem man den Modus ändern kann:
> 
> ![grafik](https://github.com/Julius-Babies/VPlanPlus/assets/66371497/8f3706d7-06ee-40eb-b0d8-f6e62ba4a7e7)
> 
> 

Servus!
Soweit ich weiß, werden bei uns nur die mobdaten veröffentlicht. Diese Wochenplan Endpoints etc. funktionieren alle nicht

**Comment by SachsenspieltCoding** [comment]
Nette Website btw., hat mir gut gefallen

**Comment by Julius-Babies** [comment]
> Nette Website btw., hat mir gut gefallen

Hattest du SSL Fehler?

> Soweit ich weiß, werden bei uns nur die mobdaten veröffentlicht. Diese Wochenplan Endpoints etc. funktionieren alle nicht

Dann muss ich da nochmal schauen. Die Klassenliste muss ja auch irgendwie bei den mobdaten ankommen. Wenn ich die verwende, wird wplan nur noch für Lehrer- und Raumlisten verwendet, was seit v0.8-alpha optional ist.

**Comment by Julius-Babies** [comment]
Kannst du mir per Mail (julvin.babies@gmail.com) die Zugangsdaten deiner Schule zukommen lassen? Dann kann ich mir die Gegebenheiten dort mal  genauer ansehen :)

**Comment by SachsenspieltCoding** [comment]
Ich hatte SSL Fehler ja, das war aber am Nachmittag als ich mir das angeschaut habe.

Die Klassenliste kannst du dir, abhängig von deiner internen Struktur, aber auch einfach selber bauen. Wenn du die Klassen als Array hast (was ja von XML mehr oder weniger vorgegeben wird), dann kannst du die ja einfach mappen

**Comment by Julius-Babies** [comment]
Würde relativ viel Restrukturierung bedeuten, da die App zunächst alle Metadaten sammelt und erst nach der Klassenwahl den ersten Plan lädt. `https://stundenplan24.de/10000000/mobil/mobdaten/Klassen.xml` scheint aber eine ähnliche Struktur zu haben.

**Comment by Julius-Babies** [comment]
Sowas wie Name der Schule - der ist leider essentiell und nicht vorhanden in den Mobdaten.

**Comment by Julius-Babies** [comment]
Ihr habt ja ein spannendes Setup. Umso interessanter, dass deine Schule trotzdem die Ordnerstruktur für wplan hat. Bei einer zufälligen Nummer, erscheint die Fehlermeldung, dass die Schulnummer nicht existiert, bei deiner Schule versucht er es wenigstens.
Muss man nicht verstehen...

**Comment by SachsenspieltCoding** [comment]
_Hab dir die Zugangsdaten geschickt.

Das mit den Metadaten ist dann natürlich doof, mit den VpMobil Endpoints kommst du da nicht ran._

GitHub hat gerade nicht geladen... Ich bin ja mal gespannt wie die alle Schulen migrieren wollen, aber gut. 
Warum unsere Schule so unglaublich wenig bereitstellt weiß ich auch nicht, hätte aber mit gescheiter Software auch verhindert werden können. Aber gut, muss Indiware selber wissen, professionell und modern ist anders

**Comment by SachsenspieltCoding** [comment]
Falls es dich interessiert: Ich habe heute meinen eigenen Indiware-Parser als separates Projekt veröffentlicht ([indiware-api](https://github.com/Vertretungsapp/indiware-api))

Ich komme halt ohne die Metadaten, Raum- und Lehrerpläne klar, da ich mir das alles selber aus dem Schüler Vplan zusammenbaue

**Comment by Julius-Babies** [comment]
Ist auch ein Ansatz. Mein Bruder geht aufs Tschirnhaus Gymnasium, die stellen die Lehrer- und Raumpläne nicht dem schueler zur Verfügung, seit dem letzten Release werden Räume und Lehrer auch anhand der Schülerpläne gesammelt und eingetragen - sofern sie noch nicht existieren. Die können dann halt keine Lehrer- und Raumprofile anlegen, die Suche nach den Entitäten geht jedoch.

**Comment by SachsenspieltCoding** [comment]
Ja gut, das Problem hab ich nicht, oder zumindest nicht in diesem Ausmaß

**Comment by Julius-Babies** [comment]
Das stimmt, wenn dur nur von Mobdaten ausgehst, kann dir sowas nicht passieren.

Ich werde demnächst auch Raum- und Lehrerprofile bei diesen Schuhen freischalten, sobald eben einmal Daten geladen wurden und wenigstens ein paar Lehrer und Räume bekannt sind.
